### ISSUE TITLE
Localtunnel version of site is broken

### ISSUE THREAD

**Issue by mojenmojen** [wplib/wplib-box#176] opened 2017-01-27 00:14 UTC
I'm able to get localtunnel working using this:

vagrant ssh
lt --port 80

But when I type in the URL to view the site on a mobile device the formatting is wrong and all of the image links are broken. Then, when I click on a link it goes to the wplib URL which of course doesn't work at all.

What do I need to do to get this working correctly? I'd like to be able to preview the site as it appears locally.

The only change I've made to the standard installation is the WP layout using this command:

box set-directory-layout-standard

**Comment by mikeschinkel** [comment] 2017-01-27 00:15
@mojenmojen Can you check your view source to see where the stylesheet urls and broken images are pointing to?

**Comment by mojenmojen** [comment] 2017-01-27 00:42
Ok, looking at view source is interesting. All of the broken images are pointing to the wplib URL, but other things, like the JavaScript, have the wplib URL replaced with the localtunnel.me URL.

Is the localtunnel.me URL supposed to automatically replace the wplib one?

**Comment by mikeschinkel** [comment] 2017-01-27 00:52
@mojenmojen Quite frankly I am not sure. We added it because people asked for it, but we've never used ourselves.

@clubdeuce implemented localtunnel on WPLib Box so he may know better.  And I honestly do not know how much he tested it with live WordPress websites.  

Seems the issue is absolute URLs:  

- https://github.com/localtunnel/localtunnel/issues/103
- https://github.com/davezuko/react-redux-starter-kit/issues/275

I think the solution would be to write a plugin that uses `ob_start();` before any output and `$html = ob_get_clean();` in a `'shutdown'` hook and then use a regular expression to change wplib URLs to the localtunnel.me URL.

Is this something you think you can write?  I think we should include with WPLib Box but I won't have time to write it tonight.  If you do write it can you reply with a link to a Gist?

**Comment by mojenmojen** [comment] 2017-01-28 20:06
I tried the solution you described by modding an existing plugin called Dynamic Hostname (https://wordpress.org/plugins/dynamic-hostname/) but I got the same result. It is entirely possible that I didn't do it correctly though.

Incidentally, I also tried using Vagrant share and I got that working, but it gave the same output as localtunnel.me.

We're nearing a launch so I don't have more time to spend on it. I'll just push to a live staging site and use that for now. Perhaps someone else will input on this in the meanwhile.

**Comment by mikeschinkel** [comment] 2017-01-28 21:29
@mojenmojen Bummer.  Well, good luck with the launch.  If you have time after the launch I will be happy to screenshare with you _(using ScreenHero; I can invite you)_ to help figure out what is happening; just let me know.

**Comment by mojenmojen** [comment] 2017-06-14 22:27
A late response here, but I managed to get this working using the tunnel option in Browsersync.

**Comment by mikeschinkel** [comment] 2017-06-14 22:28
@mojenmojen thanks.  So we should close this or we still need to fix?

**Comment by mojenmojen** [comment] 2017-06-14 22:33
My apologies, this can be closed.

**Comment by mikeschinkel** [comment] 2017-06-14 22:34
Cool, thanks!

**Comment by mikeschinkel** [comment] 2017-12-27 09:59
Closing this when it should have been closed long ago...

**Closed by mikeschinkel** 2017-12-27 09:59 UTC
