### ISSUE TITLE
Unable to run wp-cli commands

### ISSUE THREAD

**Issue by przemekcichon** [wplib/wplib-box#261] opened 2017-06-21 21:32 UTC
Hi Team,

Here is another one on fresh, out of the box install of wplib box. 

When I am trying to run any wp-cli command like for example wp --info it gives me the error below:
```bash
vagrant@loc:~$ wp --info
Could not open input file: /usr/local/bin/wp
```

when I go to `/usr/local/bin/` and run `php wp --info` I get the message as below:
```
vagrant@loc:/usr/local/bin$ php wp --info
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/src/myapp/wp:3
Stack trace:
#0 {main}
  thrown in /usr/src/myapp/wp on line 3
```

Please let me know in case I should add anything more here.

Thank you,
Przemek

**Comment by mikeschinkel** [comment] 2017-06-21 21:59
Hi @przemekcichon - We are painfully aware of this issue and plan to fix for `0.16.0` In the near term the best option is to use our most-rock solid version `0.11.2` instead.  To do so add this to your `Vagrantfile` and run `vagrant reload`:

    config.vm.box_version = "0.11.2"

If you have not backed up your database first run `vagrant ssh` then `box backup-db` which will create a `current.sql` file in `/sql/`.  

Now run `vagrant reload` and then `vagrant ssh`.  Change to `/vagrant/sql` and renamed `current.sql` to another filename, like `export.sql` then run `box import-db export.sql`. That should get you up and working.

-------------
Why the problems with `0.15.0`?  As part of our longer term plan we have been moving to using Docker to allow for mix-and-match web server, database server, etc.  Unfortunately we did not realize the extent of usability issues moving to Docker containers would cause until recently, so we are working to resolve those issues, and we hope to solve most of them by our next release, `0.16.0`.  

Normally we have 3 week cycles but because of a client requirement this release is probably going to take several more weeks at least before it can see the light of day.

**Comment by clubdeuce** [comment] 2017-06-22 17:08
@przemekcichon @mikeschinkel Unfortunately, the `vagrant reload` will _*not*_ create a new version of the box based upon the newly specified box image version. After specifying the `config.vm.box_version`, you will have to do a `vagrant destroy` and then `vagrant up`. Of course, the database backup is still necessary.

**Comment by clubdeuce** [comment] 2017-06-22 17:10
This is a duplicate of #232. As a result, I am closing this issue.

**Closed** 2017-06-22 17:11 UTC
Labels: duplicate
