### ISSUE TITLE
Simple splash screen on SSH.

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#249] opened 2017-05-23 19:13 UTC
Let's replace the Ubuntu splash screen with a simple one in the same form that displays box name and version.

**Comment by clubdeuce** [comment] 2017-05-23 20:36
This is a duplicate of #134.

**Comment by mikeschinkel** [comment] 2017-05-23 20:44
It had been so long since I wrote that, I assumed it must have gotten deleted, since it's such an easy fix. ;-)

**Closed** 2017-06-06 18:00 UTC
Labels: duplicate, enhancement
