### ISSUE TITLE
File permissions issue when updating Twenty Sixteen theme on fresh install.

### ISSUE THREAD

**Issue by oxygensmith** [wplib/wplib-box#172] opened 2016-12-13 21:19 UTC
![wplib-box-file-permissions-issue-fresh-install-click-to-update-2016](https://cloud.githubusercontent.com/assets/51263/21159591/725116bc-c147-11e6-8285-e228d3b322ab.png)

**Comment by mikeschinkel** [comment] 2017-12-27 10:01
I believe this is a duplicate of #266, which I have updated recently _(which is why I am closing this one and not that one.)_

**Closed by mikeschinkel** 2017-12-27 10:01 UTC
Labels: duplicate
