### ISSUE TITLE
Strange (empty) file in /var/www folder

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wplib/wplib-box#46] opened 2016-04-20 02:19 UTC
While looking at the contents of `/var` to see if `/var/www/content` was there (result of #43 ), I ssh-ed into the VM:

```sh
vagrant@wplib:/var/www$ ll
total 16
-rw-r--r--  1 vagrant vagrant    0 Apr 20 02:14 =
drwxr-xr-x  1 vagrant vagrant  238 Apr 20 02:14 ./
drwxr-xr-x 12 root    root    4096 Apr 20 02:08 ../
-rw-r--r--  1 vagrant vagrant    0 Apr 20 02:14 default:
-rw-r--r--  1 vagrant vagrant   85 Apr 20 02:02 index.php
-rw-r--r--  1 vagrant vagrant  128 Apr 20 02:02 wp-config-local.php
-rw-r--r--  1 vagrant vagrant 2558 Apr 20 02:02 wp-config.php
```

The result of a `cat` is that it is empty

```sh
vagrant@wplib:/var/www$ cat default\: 
vagrant@wplib:/var/www$
```

**Comment by clubdeuce** [comment] 2016-04-20 02:21
@franz-josef-kaiser: Per the [quickstart-instructions](https://github.com/wplib/wplib-box#quickstart), you skipped the `composer install`. That is why you encountered this error.

**Comment by franz-josef-kaiser** [comment] 2016-04-20 02:40
@clubdeuce I have a hard time seeing a connection between the `default:` file and composer not having installed the dependencies yet.

**Comment by clubdeuce** [comment] 2016-04-20 03:22
@franz-josef-kaiser: My apologies, I misunderstood the issue.

Here is the output from my box:

```
vagrant@wplib:/var/www$ ll
total 20
drwxr-xr-x  1 vagrant vagrant  306 Apr 19 15:16 ./
drwxr-xr-x 12 root    root    4096 Apr 19 16:01 ../
drwxr-xr-x  1 vagrant vagrant  238 Apr 11 16:30 content/
-rw-r--r--  1 vagrant vagrant   85 Apr  5 16:30 index.php
-rw-r--r--  1 vagrant vagrant   17 Apr  5 16:47 phpinfo.php
drwxr-xr-x  1 vagrant vagrant  238 Apr 19 04:10 vendor/
drwxr-xr-x  1 vagrant vagrant  680 Apr 19 04:10 wp/
-rw-r--r--  1 vagrant vagrant  128 Apr  5 16:30 wp-config-local.php
-rw-r--r--  1 vagrant vagrant 2558 Apr 19 15:16 wp-config.php
```

Can you confirm the box version you are using ( `vagrant box list`)?

**Comment by clubdeuce** [comment] 2016-05-09 18:51
I am unable to reproduce this behavior. Closing issues

**Closed** 2016-05-09 18:51 UTC
