### ISSUE TITLE
Cant update blog or install any additions

### ISSUE THREAD

**Issue by BoxMediaUK** [wplib/wplib-box#245] opened 2017-05-22 12:08 UTC
Got box up and running, but you cannot update wordpress core from the admin page as it cannot connect to the outside repository on wordpress, it asks for a hostname, ftp password etc. 

Not sure if this is standard practise but have not experienced this before on other boxes..

**Comment by BoxMediaUK** [comment] 2017-05-23 09:26
All pretty standard straight from the install!

Using Mac Os 10.12.5

VirtualBox 5.1.22 r115126

Box 0.14

https://gist.github.com/BoxMediaUK/ac66a66ae39919390b4d3d90774acf7e.js

![screenshot 2017-05-23 10 26 04](https://cloud.githubusercontent.com/assets/158435/26347700/47370c46-3fa2-11e7-8663-8e35e98f8269.png)

**Comment by mikeschinkel** [comment] 2017-05-23 09:47
@clubdeuce I can confirm with a brand new clone of WPLib Box that I get the same thing when I attempt to update WordPress core.  The only thing I did prior to `vagrant up` was run this:

    echo test2.dev > HOSTNAME

<img width="671" alt="wp-update" src="https://cloud.githubusercontent.com/assets/153285/26348589/29944324-3f7b-11e7-8d89-f5d0d67375e7.png">

**Comment by clubdeuce** [comment] 2017-05-23 15:20
This is caused by permissions issues with user/group under which the PHP-FPM service is running in the Docker container as compared to how the shared volumes are mounted.

As a short term fix with box versions `0.14.0` and `0.15.0`, you can switch to PHP7.1 _(`box php7.1`)_  and the update will work as expected.

**Comment by BoxMediaUK** [comment] 2017-05-23 17:18
That did the job - thanks

I changed to the `box php7.1` in the project.json file, then reloaded the vagrant box and then all was working as expected..

**Comment by clubdeuce** [comment] 2017-05-23 17:19
@BoxMediaUK Very good. I apologize for the difficulties.

**Comment by mikeschinkel** [comment] 2017-05-23 19:11
> _"Is there a command to detect version number of the box we are running?"_

Not yet, but there [**should be**](https://github.com/wplib/wplib-box/issues/248). Thanks for reminding us.

**Comment by mikeschinkel** [comment] 2017-05-23 19:14
@clubdeuce oops, sorry for closing this eraLief.

**Comment by mikeschinkel** [comment] 2017-12-27 07:59
Even though this one came in earlier we are going to use #266 as the issue to track this issue because I posted requirements to it before revisiting this one.

**Closed by mikeschinkel** 2017-12-27 07:59 UTC
Labels: bug, duplicate
